#!/bin/zsh

# cd into catkin workspace root
cd $(catkin locate --workspace $(pwd))

# get list of extended workspaces
EXTENDED_WS="$(pwd)/.extended_ws"

for line in "${(@f)"$(<$EXTENDED_WS)"}"
{
  [[ ! -z "${line}" ]] && catkin config --extend ${line}
}

# catkin build -c -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=YES "$@"

jq -s 'map(.[])' build/**/compile_commands.json > compile_commands.json
