#!/bin/bash

# cd into catkin workspace root
cd "$(catkin locate --workspace "$(pwd)")"

# Check if build/ exists
[ ! -d ./build ] && echo "Not a valid catkin workspace" && exit

# get list of extended workspaces
EXTENDED_WS="$(pwd)/.extended_ws"
if [ -f "${EXTENDED_WS}" ]; then
  while IFS= read -r line; do
    [ -d "${line}" ] && catkin config --extend "${line}"
  done <"${EXTENDED_WS}"
fi

# combine compile commands
jq -s 'map(.[])' build/**/compile_commands.json >compile_commands.json
